import './globals.css'
import Link from 'next/link'


export const metadata = {
  title: 'WEb Tutorials',
  description: 'Generated by create yoodeit',
}

export default function RootLayout({ children }) {
  return (
    <html>
      <body>
      <h1><Link href='/'>WEB</Link></h1>
      <ol>
          <li><Link href='/read/1'html></Link></li>
          <li><Link href='/read/2'html></Link></li>
      </ol>
          {children}
          <ul>
            <li><Link href='/create'>Create</Link></li>
            <li><Link href='/update/1'>Update</Link></li>
            <li><input type="button" value="delete" /></li>
          </ul>
      </body>
    </html>
  )
}
